### ISSUE TITLE
Doesn't recognize files and directorys

### ISSUE THREAD

**Issue by srsalute** [ALMaclaine/replace#2] opened 2019-02-06 13:11 UTC
When i do : 
replace -h
the result is
Opção inválida - -h
Nenhum arquivo substituído

**Comment by ALMaclaine** [comment] 2019-02-07 03:03
I can't reproduce this issue.

**Comment by ALMaclaine** [comment] 2019-02-18 20:37
Closing this issue for now.

**Closed as completed by ALMaclaine** 2019-02-18 20:37 UTC
